# Generated by Django 2.2.1 on 2019-05-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birth_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='prod_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='stg_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_Code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='whs_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WH', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='whs_stg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_Code', models.ManyToManyField(related_name='storage', to='website.stg_mst')),
                ('WH', models.ManyToManyField(related_name='storage', to='website.whs_mst')),
            ],
        ),
        migrations.CreateModel(
            name='whs_inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Product_Code', models.ManyToManyField(related_name='product', to='website.prod_mst')),
                ('Store_Code', models.ManyToManyField(related_name='product', to='website.stg_mst')),
            ],
        ),
        migrations.CreateModel(
            name='stg_inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Closing_Inventory', models.IntegerField()),
                ('Date', models.DateField()),
                ('Product_Code', models.ManyToManyField(related_name='warehouse', to='website.prod_mst')),
                ('Store_Code', models.ManyToManyField(related_name='warehouse', to='website.stg_mst')),
            ],
        ),
    ]
