# Generated by Django 2.2.1 on 2019-05-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='required_qty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_qty', models.IntegerField()),
                ('Product_Code', models.ManyToManyField(related_name='requiredqty', to='website.prod_mst')),
            ],
        ),
        migrations.CreateModel(
            name='replenishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repl_qty', models.IntegerField()),
                ('Product_Code', models.ManyToManyField(related_name='replenishment', to='website.prod_mst')),
                ('Store_Code', models.ManyToManyField(related_name='replenishment', to='website.stg_mst')),
                ('WH', models.ManyToManyField(related_name='replenishment', to='website.whs_mst')),
            ],
        ),
    ]
